name: Playwright tests
on: push

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2
        # Use the official setup-node action (sets up Node.js):
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: yarn playwright install-deps
      - name: Run e2e tests
        run: yarn dev
      - name: Run tests
        run: yarn playwright test
